name: Deploy INAAS Backend

on:
  push:
    branches:
      - dev
      - staging
      - prod
    paths:
      - 'Backend/**'

env:
  AWS_REGION: us-east-1
  ECR_REPO: inaas-raw

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------------------
      # Set IMAGE_TAG based on branch
      # ---------------------------
      - name: Set image tag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Deploying branch: $BRANCH_NAME"

      # ---------------------------
      # Configure AWS credentials
      # ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------------------
      # Login to ECR
      # ---------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------------------
      # Build Docker Image
      # ---------------------------
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./Backend

      # ---------------------------
      # Tag Image
      # ---------------------------
      - name: Tag image
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
          339713066436.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      # ---------------------------
      # Push Image
      # ---------------------------
      - name: Push image to ECR
        run: |
          docker push 339713066436.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
